### ISSUE TITLE
Roadmap 0.1

### ISSUE THREAD

**Issue by ipfans** [ipfans/VNReborn#1]
- [ ] Base framework for game searching and recognition. 
- [ ] OCR Engine: Japanese OCR.
- [ ] Text(JP) translation by network services(Google Translate?).
- [ ] TextPreview window(maybe console only).
